FROM node

RUN mkdir -p /usr/src/{app,config}
WORKDIR /usr/src/app

COPY realtime/package.json /usr/src/app/
RUN JOBS=MAX npm install

EXPOSE 8080

COPY config/ /usr/src/config/
COPY realtime/ /usr/src/app/
CMD ["node", "server.js"]
