FROM nginx

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY . /usr/src/app/

RUN apt-get update && \
    apt-get install -y git nodejs nodejs-legacy npm && \
    rm -rf /var/lib/apt/lists/*

RUN npm install
RUN ./node_modules/bower/bin/bower --allow-root install
