FROM nginx

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y git nodejs nodejs-legacy npm && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g bower

COPY client/package.json /usr/src/app/
RUN npm install

COPY client/bower.json /usr/src/app/
RUN bower --allow-root install

COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY client/ /usr/src/app/
